config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'top' => 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all.order(created_at: :desc)
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      redirect_to "/books/#{@book.id}"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:success] = 'Book was successfully destroyed.'
      redirect_to "/books"
    else
      redirect_to "/books"
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing  Book</h1>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |b| %>
 <div class="field">
    <label for="book_title">Title</label>
    <%= b.text_field :title, id: "book_title" %>
  </div>
  <div class="field">
    <label for="book_body">Body</label>
    <%= b.text_area :body, id: "book_body"%>
  </div>
  <div class="actions">
    <%= b.submit 'Update Book' %>
  </div>
<% end %>

<%= link_to "Show", "/books/#{@book.id}" %>
<!--|-->
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<div id="notice">
  <p><%= flash[:success] %></p>
</div>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @books.each do |b| %>
    <tbody>
      <tr>
        <td><%= b.title %></td>
        <td><%= b.body %></td>
        <td><%= link_to "show", "/books/#{b.id}" %></td>
        <td><%= link_to "edit", "/books/#{b.id}/edit" %></td>
        <td><%= link_to "Destroy", "/books/#{b.id}", method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    </tbody>
  <% end %>
</table>

<%= render template: "/books/new" %>

app/views/books/new.html.erb
<h2>New book</h2>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<!--model注意-->
<%= form_with model:@book, url:"/books", local:true do |b| %>
  <div class="field">
    <label for="book_title">Title</label>
    <%= b.text_field :title, id: "book_title" %>
  </div>
  <div class="field">
    <label for="book_body">Body</label>
    <%= b.text_area :body, id: "book_body"%>
  </div>

  <%= b.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div id="notice">
  <p><%= flash[:success] %></p>
</div>

<p><strong>Title: </strong><%= @book.title %></p>
<p><strong>Body: </strong><%= @book.body %></p>

<%= link_to "Edit", "/books/#{@book.id}/edit" %>
|
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>